config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root to: 'daily_scorecards#today'

  get '/settings', to: 'users#edit', as: 'settings'
  patch '/settings', to: 'users#update'

  get '/', to: 'daily_scorecards#today', as: 'daily_scorecard_today'

  get '/:year/:month/:day', to: 'daily_scorecards#show', as: 'daily_scorecard',
    constraints: { :year => /\d+/, :month => /\d\d?/, :day => /\d\d?/ }

  scope '/:year/:month/:day' do
    resources :meals, only: [:new, :create]
  end

  resources :meals, only: [:edit, :update, :destroy] do
    resources :foods, except: [:index, :show]
  end
end

app/models/food.rb
require_dependency 'diet_scorecard/food_type'

class Food < ActiveRecord::Base
  belongs_to :meal
  serialize :servings, Hash

  validates :name, presence: true

  @@servings_fields = []

  DietScorecard::FoodType.each do |ft|
    field_name = "#{ft.key}_servings".to_sym
    @@servings_fields << field_name

    define_method(field_name) do
      servings_of(ft.key)
    end

    define_method("#{field_name}=") do |value|
      servings[ft.key] = value
    end

    validates field_name, numericality: true
  end

  def servings_of(food_type)
    servings.fetch(food_type, 0).to_f
  end

  def self.servings_fields
    @@servings_fields.dup
  end

  def servings_fields
    self.class.servings_fields
  end

  delegate :name, to: :meal, prefix: true
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  helper :food_type

  service(:meals) { Meal.for_user_id(current_user.id) }

  template_attr :food

  def new
    self.food = meal.new_food
  end

  def create
    self.food = meal.create_food(food_params)
    if food.valid?
      redirect_to daily_scorecard_path(daily_scorecard_path_params)
    else
      render action: :new, status: 422
    end
  end

  def destroy
    self.food = meal.destroy_food(params[:id])
    flash[:notice] = [{key: '.food_deleted', food_name: food.name}]
    redirect_to daily_scorecard_path(daily_scorecard_path_params)
  end

  def edit
    self.food = meal.find_food(params[:id])
  end

  def update
    self.food = meal.update_food(params[:id], food_params)
    if food.valid?
      redirect_to daily_scorecard_path(daily_scorecard_path_params)
    else
      render action: :edit, status: 422
    end
  end

  def daily_scorecard_path_params
    date_params_from(meal.consumed_at)
  end
  helper_method :daily_scorecard_path_params

  private

  def meal
    @meal ||= meals.find(params.require(:meal_id))
  end

  def food_params
    params.require(:food).permit(:name, *Food.servings_fields)
  end
end

app/views/foods/_form.html.erb
<% if food.errors.any? %>
  <div class="alert alert-danger" roler="alert">
    <%=t 'validation_errors_present' %>
  </div>
<% end %>

<%= form_for food, url: form_url do |f| %>
  <div class="form-group <%= form_error_classes(food.errors[:name]) %>">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: t('.food_name_placeholder') %>
    <% if food.errors[:name].any? %>
      <span class="glyphicon glyphicon-remove form-control-feedback" aria-hidden="true"></span>
      <span class="help-block"><%= food.errors[:name].join(', ') %></span>
    <% end %>
  </div>

  <%= render partial: 'servings_field', collection: food.servings_fields, locals: {f: f} %>

  <div class="form-group">
    <%= f.submit t('.save_food'), class: 'btn btn-primary' %>
    <%= link_to t('cancel_button'), daily_scorecard_path(daily_scorecard_path_params), class: 'btn btn-default' %>
  </div>
<% end %>

app/views/foods/_servings_field.html.erb
<div class="form-group">
  <%= f.label servings_field %>
  <%= f.select servings_field, servings_options_for_select, {}, class: 'form-control' %>
</div>

app/views/foods/edit.html.erb
<h1><%=t '.edit_food_header', name: food.name, meal_name: food.meal_name %></h1>

<%= render partial: 'form', locals: {food: food, form_url: meal_food_path(food.meal, food)} %>

app/views/foods/new.html.erb
<h1><%=t '.new_food_header', meal_name: food.meal_name %></h1>

<%= render partial: 'form', locals: {food: food, form_url: meal_foods_path(food.meal)} %>