config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  root to: 'daily_scorecards#today'

  get '/settings', to: 'users#edit', as: 'settings'
  patch '/settings', to: 'users#update'

  get '/', to: 'daily_scorecards#today', as: 'daily_scorecard_today'

  get '/:year/:month/:day', to: 'daily_scorecards#show', as: 'daily_scorecard',
    constraints: { :year => /\d+/, :month => /\d\d?/, :day => /\d\d?/ }

  scope '/:year/:month/:day' do
    resources :meals, only: [:new, :create]
  end

  resources :meals, only: [:edit, :update, :destroy] do
    resources :foods, except: [:index, :show]
  end
end

app/controllers/daily_scorecards_controller.rb
class DailyScorecardsController < ApplicationController
  helper :food_type

  service(:clock) { Time.zone }

  service(:daily_scorecards) {
    require 'diet_scorecard/daily_scorecard'
    DietScorecard::DailyScorecard
  }

  service(:meals) { Meal }

  template_attr :daily_scorecard, :running_average_score

  def today
    render_daily_scorecard clock.now
  end

  def show
    render_daily_scorecard clock.local(params[:year], params[:month], params[:day])
  end

  private

  def scoped_meals
    @scoped_meals ||= meals.for_user_id(current_user.id)
  end

  def render_daily_scorecard(date)
    self.daily_scorecard = daily_scorecards.new(
      date: date,
      meals_service: scoped_meals
    )

    start_date = date.to_date - 6
    stop_date = date.to_date - 1
    historical_cards = (start_date..stop_date).map { |date|
      daily_scorecards.new(date: date, meals_service: scoped_meals)
    }
    historical_total_score = historical_cards.sum(&:score)
    historical_avg = historical_total_score / historical_cards.size
    self.running_average_score = historical_avg
    render action: :show
  end
end

app/helpers/daily_scorecards_helper.rb
module DailyScorecardsHelper
  def total_points_score_type(daily_scorecard)
    ratio = daily_scorecard.total_points.to_f / daily_scorecard.possible_points.to_f
    case ratio
    when 0.75..Float::INFINITY
      'success'
    when 0.5...0.75
      'info'
    when 0.25...0.5
      'warning'
    else
      'danger'
    end
  end
end

app/views/daily_scorecards/_food_type_scorecard.html.erb
<tr>
  <th><%=t "food_type.#{food_type_scorecard.food_type_key}" %></th>
  <td class="text-center"><%= number_with_precision(food_type_scorecard.servings_consumed, strip_insignificant_zeros: true) %></td>
  <td class="text-center"><%= formatted_serving_recomendation(food_type_scorecard.servings_recommended) %></td>
  <td class="text-center"><%= food_type_scorecard.points_earned %></td>
</tr>

app/views/daily_scorecards/_meal.html.erb
<thead>
<tr class="info">
  <th colspan=3">
    <div class="col-md-5">
      <h3><%= meal.name %> <small><%=t '.consumed_at',
        time: l(meal.consumed_at, format: :time) %></small></h3>
    </div>
    <div class="col-md-7 text-right">
      <%= link_to(t('.add_food_button'), new_meal_food_path(meal_id: meal.id),
                  class: 'btn btn-success') %>
      <%= link_to(t('.edit_meal_button'), edit_meal_path(meal),
                  class: 'btn btn-default') %>
      <%= button_to(t('.delete_meal_button'), meal_path(meal), method: :delete,
                    class: 'btn btn-danger', data: {confirm: "Are you sure you want to delete #{meal.name}?"}) %>
    </div>
  </td>
</tr>
</thead>
<tbody>
<% meal.foods.each do |food| %>
  <tr>
    <th><%= food.name %></th>
    <td>
      <ul>
        <% food_types.each do |ft| %>
          <%
            servings = food.servings_of(ft.key)
            next if servings == 0
          %>
          <li><%=t "food_type.#{ft.key}"%>: <%= number_with_precision(servings, strip_insignificant_zeros: true) %></li>
        <% end %>
      </ul>
    </td>
    <td class="text-right"><%= link_to(t('.edit_food_button'), edit_meal_food_path(food.meal, food),
                    class: 'btn btn-default') %>
    <%= button_to(t('.delete_food_button'), meal_food_path(food.meal, food),
                  method: :delete, class: 'btn btn-danger',
                  data: {confirm: "Are you sure you want to delete #{food.name}?"}) %></td>
  </tr>
<% end %>
</tbody>

app/views/daily_scorecards/show.html.erb
<h1><%=t '.scorecard_for', date: l(daily_scorecard.date, format: :long) %></h1>

<nav>
  <ul class="pager">
    <li><%= link_to t('.previous_day_link'), daily_scorecard_path(daily_scorecard.previous.to_param), class: 'previous' %></li>
    <li><%= link_to t('.today_link'), daily_scorecard_today_path %></li>
    <li><%= link_to t('.next_day_link'), daily_scorecard_path(daily_scorecard.next.to_param), class: 'next' %></li>
  </ul>
</nav>

<div class="row">
  <div id="daily_scorecard_summary" class="col-lg-4">
    <h2 class="text-<%= total_points_score_type(daily_scorecard) %>" id="dqs_total_points">
      <%=t '.total_points' %>: <%= daily_scorecard.score.round %>%
      <span class="glyphicon glyphicon-<%= total_points_score_type(daily_scorecard) %>" aria-hidden="true"></span>
    </h2>
    <p><%=t '.running_average' %>: <%= running_average_score.round %>%</p>
    <h2><%=t '.summary_heading' %></h2>
    <table class="table">
      <thead>
        <tr>
          <th></th>
          <th><%=t '.servings_consumed_heading' %></th>
          <th><%=t '.servings_recomended_heading' %></th>
          <th><%=t '.points_earned_heading' %></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: 'food_type_scorecard', collection: daily_scorecard.food_type_scorecards %>
      </tbody>
    </table>
  </div>

  <div class="col-lg-8">
    <h2>
      <%=t '.meals_heading' %>
      <%= link_to(t('.add_meal_button'), new_meal_path(daily_scorecard.to_param),
        class: 'btn btn-success') %>
    </h2>
    <div class="row">
      <table class="table">
        <%= render partial: 'meal', collection: daily_scorecard.meals %>
      </table>
    </div>
  </div>
</div>